export type LiveFlightOffer = {
  id: string;
  airline: string;
  flight_number: string;
  from: string;
  to: string;
  departure_at: string;
  arrival_at: string;
  return_from?: string;
  return_to?: string;
  return_departure_at?: string;
  return_arrival_at?: string;
  return_airline?: string;
  return_flight_number?: string;
  return_duration?: string;
  return_stops?: number;
  stop_details?: string;
  return_stop_details?: string;
  baggage_information?: string;
  return_baggage_information?: string;
  duration: string;
  stops?: number;
  price: number;
  currency: string;
  cabin?: string;
};

export type FlightDetailsDraft = {
  has_return: boolean;
  airline: string | null;
  flight_number: string | null;
  from: string | null;
  to: string | null;
  departure_at: string | null;
  arrival_at: string | null;
  duration: string | null;
  stops: number | null;
  price: number | null;
  currency: string | null;
  cabin: string | null;
  return_airline: string | null;
  return_flight_number: string | null;
  return_from: string | null;
  return_to: string | null;
  return_departure_at: string | null;
  return_arrival_at: string | null;
  return_duration: string | null;
  return_stops: number | null;
  stop_details: string | null;
  return_stop_details: string | null;
  baggage_information: string | null;
  return_baggage_information: string | null;
};
