/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedDailyReportsRouteImport } from './routes/_authenticated/daily-reports'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedEnquiriesRouteImport } from './routes/_authenticated/enquiries'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedFollowUpsRouteImport } from './routes/_authenticated/follow-ups'
import { Route as AuthenticatedGmailRouteImport } from './routes/_authenticated/gmail'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedItineraryBuilderRouteImport } from './routes/_authenticated/itinerary-builder'
import { Route as AuthenticatedItineraryLibraryRouteImport } from './routes/_authenticated/itinerary-library'
import { Route as AuthenticatedItineraryProposalsRouteImport } from './routes/_authenticated/itinerary-proposals'
import { Route as AuthenticatedMessagingRouteImport } from './routes/_authenticated/messaging'
import { Route as AuthenticatedOperationsRouteImport } from './routes/_authenticated/operations'
import { Route as AuthenticatedPackagesRouteImport } from './routes/_authenticated/packages'
import { Route as AuthenticatedPayablesRouteImport } from './routes/_authenticated/payables'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTeamTasksRouteImport } from './routes/_authenticated/team-tasks'
import { Route as AuthenticatedWacrmRouteImport } from './routes/_authenticated/wacrm'
import { Route as ItineraryShareTokenRouteImport } from './routes/itinerary-share.$token'
import { Route as AuthenticatedBookingsIndexRouteImport } from './routes/_authenticated/bookings.index'
import { Route as AuthenticatedBookingsBookingIdRouteImport } from './routes/_authenticated/bookings.$bookingId'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers.index'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers.$customerId'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated/groups.index'
import { Route as AuthenticatedGroupsGroupIdRouteImport } from './routes/_authenticated/groups.$groupId'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads.index'
import { Route as AuthenticatedLeadsLeadIdRouteImport } from './routes/_authenticated/leads.$leadId'
import { Route as AuthenticatedQuotationsIndexRouteImport } from './routes/_authenticated/quotations.index'
import { Route as AuthenticatedQuotationsQuotationIdRouteImport } from './routes/_authenticated/quotations.$quotationId'
import { Route as ApiWacrmDestinationsRouteImport } from './routes/api.wacrm.destinations'
import { Route as ApiWacrmFlowCompletedRouteImport } from './routes/api.wacrm.flow-completed'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailyReportsRoute =
  AuthenticatedDailyReportsRouteImport.update({
    id: '/daily-reports',
    path: '/daily-reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnquiriesRoute = AuthenticatedEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowUpsRoute = AuthenticatedFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGmailRoute = AuthenticatedGmailRouteImport.update({
  id: '/gmail',
  path: '/gmail',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedItineraryBuilderRoute =
  AuthenticatedItineraryBuilderRouteImport.update({
    id: '/itinerary-builder',
    path: '/itinerary-builder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItineraryLibraryRoute =
  AuthenticatedItineraryLibraryRouteImport.update({
    id: '/itinerary-library',
    path: '/itinerary-library',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItineraryProposalsRoute =
  AuthenticatedItineraryProposalsRouteImport.update({
    id: '/itinerary-proposals',
    path: '/itinerary-proposals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagingRoute = AuthenticatedMessagingRouteImport.update({
  id: '/messaging',
  path: '/messaging',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperationsRoute = AuthenticatedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPackagesRoute = AuthenticatedPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayablesRoute = AuthenticatedPayablesRouteImport.update({
  id: '/payables',
  path: '/payables',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamTasksRoute = AuthenticatedTeamTasksRouteImport.update({
  id: '/team-tasks',
  path: '/team-tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWacrmRoute = AuthenticatedWacrmRouteImport.update({
  id: '/wacrm',
  path: '/wacrm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ItineraryShareTokenRoute = ItineraryShareTokenRouteImport.update({
  id: '/itinerary-share/$token',
  path: '/itinerary-share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBookingsIndexRoute =
  AuthenticatedBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsBookingIdRoute =
  AuthenticatedBookingsBookingIdRouteImport.update({
    id: '/bookings/$bookingId',
    path: '/bookings/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupsGroupIdRoute =
  AuthenticatedGroupsGroupIdRouteImport.update({
    id: '/groups/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsLeadIdRoute =
  AuthenticatedLeadsLeadIdRouteImport.update({
    id: '/leads/$leadId',
    path: '/leads/$leadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotationsIndexRoute =
  AuthenticatedQuotationsIndexRouteImport.update({
    id: '/quotations/',
    path: '/quotations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotationsQuotationIdRoute =
  AuthenticatedQuotationsQuotationIdRouteImport.update({
    id: '/quotations/$quotationId',
    path: '/quotations/$quotationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiWacrmDestinationsRoute = ApiWacrmDestinationsRouteImport.update({
  id: '/api/wacrm/destinations',
  path: '/api/wacrm/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWacrmFlowCompletedRoute = ApiWacrmFlowCompletedRouteImport.update({
  id: '/api/wacrm/flow-completed',
  path: '/api/wacrm/flow-completed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/daily-reports': typeof AuthenticatedDailyReportsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/enquiries': typeof AuthenticatedEnquiriesRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/gmail': typeof AuthenticatedGmailRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/itinerary-builder': typeof AuthenticatedItineraryBuilderRoute
  '/itinerary-library': typeof AuthenticatedItineraryLibraryRoute
  '/itinerary-proposals': typeof AuthenticatedItineraryProposalsRoute
  '/messaging': typeof AuthenticatedMessagingRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/payables': typeof AuthenticatedPayablesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/team': typeof AuthenticatedTeamRoute
  '/team-tasks': typeof AuthenticatedTeamTasksRoute
  '/wacrm': typeof AuthenticatedWacrmRoute
  '/itinerary-share/$token': typeof ItineraryShareTokenRoute
  '/bookings/$bookingId': typeof AuthenticatedBookingsBookingIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/quotations/$quotationId': typeof AuthenticatedQuotationsQuotationIdRoute
  '/api/wacrm/destinations': typeof ApiWacrmDestinationsRoute
  '/api/wacrm/flow-completed': typeof ApiWacrmFlowCompletedRoute
  '/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/groups/': typeof AuthenticatedGroupsIndexRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
  '/quotations/': typeof AuthenticatedQuotationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/daily-reports': typeof AuthenticatedDailyReportsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/enquiries': typeof AuthenticatedEnquiriesRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/gmail': typeof AuthenticatedGmailRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/itinerary-builder': typeof AuthenticatedItineraryBuilderRoute
  '/itinerary-library': typeof AuthenticatedItineraryLibraryRoute
  '/itinerary-proposals': typeof AuthenticatedItineraryProposalsRoute
  '/messaging': typeof AuthenticatedMessagingRoute
  '/operations': typeof AuthenticatedOperationsRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/payables': typeof AuthenticatedPayablesRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/team': typeof AuthenticatedTeamRoute
  '/team-tasks': typeof AuthenticatedTeamTasksRoute
  '/wacrm': typeof AuthenticatedWacrmRoute
  '/itinerary-share/$token': typeof ItineraryShareTokenRoute
  '/bookings/$bookingId': typeof AuthenticatedBookingsBookingIdRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/quotations/$quotationId': typeof AuthenticatedQuotationsQuotationIdRoute
  '/api/wacrm/destinations': typeof ApiWacrmDestinationsRoute
  '/api/wacrm/flow-completed': typeof ApiWacrmFlowCompletedRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
  '/quotations': typeof AuthenticatedQuotationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/daily-reports': typeof AuthenticatedDailyReportsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/enquiries': typeof AuthenticatedEnquiriesRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/_authenticated/gmail': typeof AuthenticatedGmailRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/itinerary-builder': typeof AuthenticatedItineraryBuilderRoute
  '/_authenticated/itinerary-library': typeof AuthenticatedItineraryLibraryRoute
  '/_authenticated/itinerary-proposals': typeof AuthenticatedItineraryProposalsRoute
  '/_authenticated/messaging': typeof AuthenticatedMessagingRoute
  '/_authenticated/operations': typeof AuthenticatedOperationsRoute
  '/_authenticated/packages': typeof AuthenticatedPackagesRoute
  '/_authenticated/payables': typeof AuthenticatedPayablesRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/team-tasks': typeof AuthenticatedTeamTasksRoute
  '/_authenticated/wacrm': typeof AuthenticatedWacrmRoute
  '/itinerary-share/$token': typeof ItineraryShareTokenRoute
  '/_authenticated/bookings/$bookingId': typeof AuthenticatedBookingsBookingIdRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/_authenticated/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
  '/_authenticated/quotations/$quotationId': typeof AuthenticatedQuotationsQuotationIdRoute
  '/api/wacrm/destinations': typeof ApiWacrmDestinationsRoute
  '/api/wacrm/flow-completed': typeof ApiWacrmFlowCompletedRoute
  '/_authenticated/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
  '/_authenticated/quotations/': typeof AuthenticatedQuotationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/activity'
    | '/daily-reports'
    | '/dashboard'
    | '/documents'
    | '/enquiries'
    | '/finance'
    | '/follow-ups'
    | '/gmail'
    | '/invoices'
    | '/itinerary-builder'
    | '/itinerary-library'
    | '/itinerary-proposals'
    | '/messaging'
    | '/operations'
    | '/packages'
    | '/payables'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/suppliers'
    | '/team'
    | '/team-tasks'
    | '/wacrm'
    | '/itinerary-share/$token'
    | '/bookings/$bookingId'
    | '/customers/$customerId'
    | '/groups/$groupId'
    | '/leads/$leadId'
    | '/quotations/$quotationId'
    | '/api/wacrm/destinations'
    | '/api/wacrm/flow-completed'
    | '/bookings/'
    | '/customers/'
    | '/groups/'
    | '/leads/'
    | '/quotations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/activity'
    | '/daily-reports'
    | '/dashboard'
    | '/documents'
    | '/enquiries'
    | '/finance'
    | '/follow-ups'
    | '/gmail'
    | '/invoices'
    | '/itinerary-builder'
    | '/itinerary-library'
    | '/itinerary-proposals'
    | '/messaging'
    | '/operations'
    | '/packages'
    | '/payables'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/suppliers'
    | '/team'
    | '/team-tasks'
    | '/wacrm'
    | '/itinerary-share/$token'
    | '/bookings/$bookingId'
    | '/customers/$customerId'
    | '/groups/$groupId'
    | '/leads/$leadId'
    | '/quotations/$quotationId'
    | '/api/wacrm/destinations'
    | '/api/wacrm/flow-completed'
    | '/bookings'
    | '/customers'
    | '/groups'
    | '/leads'
    | '/quotations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/activity'
    | '/_authenticated/daily-reports'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/enquiries'
    | '/_authenticated/finance'
    | '/_authenticated/follow-ups'
    | '/_authenticated/gmail'
    | '/_authenticated/invoices'
    | '/_authenticated/itinerary-builder'
    | '/_authenticated/itinerary-library'
    | '/_authenticated/itinerary-proposals'
    | '/_authenticated/messaging'
    | '/_authenticated/operations'
    | '/_authenticated/packages'
    | '/_authenticated/payables'
    | '/_authenticated/payments'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/suppliers'
    | '/_authenticated/team'
    | '/_authenticated/team-tasks'
    | '/_authenticated/wacrm'
    | '/itinerary-share/$token'
    | '/_authenticated/bookings/$bookingId'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/groups/$groupId'
    | '/_authenticated/leads/$leadId'
    | '/_authenticated/quotations/$quotationId'
    | '/api/wacrm/destinations'
    | '/api/wacrm/flow-completed'
    | '/_authenticated/bookings/'
    | '/_authenticated/customers/'
    | '/_authenticated/groups/'
    | '/_authenticated/leads/'
    | '/_authenticated/quotations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ItineraryShareTokenRoute: typeof ItineraryShareTokenRoute
  ApiWacrmDestinationsRoute: typeof ApiWacrmDestinationsRoute
  ApiWacrmFlowCompletedRoute: typeof ApiWacrmFlowCompletedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily-reports': {
      id: '/_authenticated/daily-reports'
      path: '/daily-reports'
      fullPath: '/daily-reports'
      preLoaderRoute: typeof AuthenticatedDailyReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enquiries': {
      id: '/_authenticated/enquiries'
      path: '/enquiries'
      fullPath: '/enquiries'
      preLoaderRoute: typeof AuthenticatedEnquiriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/follow-ups': {
      id: '/_authenticated/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof AuthenticatedFollowUpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gmail': {
      id: '/_authenticated/gmail'
      path: '/gmail'
      fullPath: '/gmail'
      preLoaderRoute: typeof AuthenticatedGmailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itinerary-builder': {
      id: '/_authenticated/itinerary-builder'
      path: '/itinerary-builder'
      fullPath: '/itinerary-builder'
      preLoaderRoute: typeof AuthenticatedItineraryBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itinerary-library': {
      id: '/_authenticated/itinerary-library'
      path: '/itinerary-library'
      fullPath: '/itinerary-library'
      preLoaderRoute: typeof AuthenticatedItineraryLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itinerary-proposals': {
      id: '/_authenticated/itinerary-proposals'
      path: '/itinerary-proposals'
      fullPath: '/itinerary-proposals'
      preLoaderRoute: typeof AuthenticatedItineraryProposalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messaging': {
      id: '/_authenticated/messaging'
      path: '/messaging'
      fullPath: '/messaging'
      preLoaderRoute: typeof AuthenticatedMessagingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operations': {
      id: '/_authenticated/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packages': {
      id: '/_authenticated/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AuthenticatedPackagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payables': {
      id: '/_authenticated/payables'
      path: '/payables'
      fullPath: '/payables'
      preLoaderRoute: typeof AuthenticatedPayablesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team-tasks': {
      id: '/_authenticated/team-tasks'
      path: '/team-tasks'
      fullPath: '/team-tasks'
      preLoaderRoute: typeof AuthenticatedTeamTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wacrm': {
      id: '/_authenticated/wacrm'
      path: '/wacrm'
      fullPath: '/wacrm'
      preLoaderRoute: typeof AuthenticatedWacrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/itinerary-share/$token': {
      id: '/itinerary-share/$token'
      path: '/itinerary-share/$token'
      fullPath: '/itinerary-share/$token'
      preLoaderRoute: typeof ItineraryShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bookings/': {
      id: '/_authenticated/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthenticatedBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/$bookingId': {
      id: '/_authenticated/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof AuthenticatedBookingsBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups/$groupId': {
      id: '/_authenticated/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/$leadId': {
      id: '/_authenticated/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AuthenticatedLeadsLeadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/': {
      id: '/_authenticated/quotations/'
      path: '/quotations'
      fullPath: '/quotations/'
      preLoaderRoute: typeof AuthenticatedQuotationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/$quotationId': {
      id: '/_authenticated/quotations/$quotationId'
      path: '/quotations/$quotationId'
      fullPath: '/quotations/$quotationId'
      preLoaderRoute: typeof AuthenticatedQuotationsQuotationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/wacrm/destinations': {
      id: '/api/wacrm/destinations'
      path: '/api/wacrm/destinations'
      fullPath: '/api/wacrm/destinations'
      preLoaderRoute: typeof ApiWacrmDestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wacrm/flow-completed': {
      id: '/api/wacrm/flow-completed'
      path: '/api/wacrm/flow-completed'
      fullPath: '/api/wacrm/flow-completed'
      preLoaderRoute: typeof ApiWacrmFlowCompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedDailyReportsRoute: typeof AuthenticatedDailyReportsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedEnquiriesRoute: typeof AuthenticatedEnquiriesRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedFollowUpsRoute: typeof AuthenticatedFollowUpsRoute
  AuthenticatedGmailRoute: typeof AuthenticatedGmailRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedItineraryBuilderRoute: typeof AuthenticatedItineraryBuilderRoute
  AuthenticatedItineraryLibraryRoute: typeof AuthenticatedItineraryLibraryRoute
  AuthenticatedItineraryProposalsRoute: typeof AuthenticatedItineraryProposalsRoute
  AuthenticatedMessagingRoute: typeof AuthenticatedMessagingRoute
  AuthenticatedOperationsRoute: typeof AuthenticatedOperationsRoute
  AuthenticatedPackagesRoute: typeof AuthenticatedPackagesRoute
  AuthenticatedPayablesRoute: typeof AuthenticatedPayablesRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTeamTasksRoute: typeof AuthenticatedTeamTasksRoute
  AuthenticatedWacrmRoute: typeof AuthenticatedWacrmRoute
  AuthenticatedBookingsBookingIdRoute: typeof AuthenticatedBookingsBookingIdRoute
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
  AuthenticatedGroupsGroupIdRoute: typeof AuthenticatedGroupsGroupIdRoute
  AuthenticatedLeadsLeadIdRoute: typeof AuthenticatedLeadsLeadIdRoute
  AuthenticatedQuotationsQuotationIdRoute: typeof AuthenticatedQuotationsQuotationIdRoute
  AuthenticatedBookingsIndexRoute: typeof AuthenticatedBookingsIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
  AuthenticatedQuotationsIndexRoute: typeof AuthenticatedQuotationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedDailyReportsRoute: AuthenticatedDailyReportsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedEnquiriesRoute: AuthenticatedEnquiriesRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedFollowUpsRoute: AuthenticatedFollowUpsRoute,
  AuthenticatedGmailRoute: AuthenticatedGmailRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedItineraryBuilderRoute: AuthenticatedItineraryBuilderRoute,
  AuthenticatedItineraryLibraryRoute: AuthenticatedItineraryLibraryRoute,
  AuthenticatedItineraryProposalsRoute: AuthenticatedItineraryProposalsRoute,
  AuthenticatedMessagingRoute: AuthenticatedMessagingRoute,
  AuthenticatedOperationsRoute: AuthenticatedOperationsRoute,
  AuthenticatedPackagesRoute: AuthenticatedPackagesRoute,
  AuthenticatedPayablesRoute: AuthenticatedPayablesRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTeamTasksRoute: AuthenticatedTeamTasksRoute,
  AuthenticatedWacrmRoute: AuthenticatedWacrmRoute,
  AuthenticatedBookingsBookingIdRoute: AuthenticatedBookingsBookingIdRoute,
  AuthenticatedCustomersCustomerIdRoute: AuthenticatedCustomersCustomerIdRoute,
  AuthenticatedGroupsGroupIdRoute: AuthenticatedGroupsGroupIdRoute,
  AuthenticatedLeadsLeadIdRoute: AuthenticatedLeadsLeadIdRoute,
  AuthenticatedQuotationsQuotationIdRoute:
    AuthenticatedQuotationsQuotationIdRoute,
  AuthenticatedBookingsIndexRoute: AuthenticatedBookingsIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
  AuthenticatedQuotationsIndexRoute: AuthenticatedQuotationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ItineraryShareTokenRoute: ItineraryShareTokenRoute,
  ApiWacrmDestinationsRoute: ApiWacrmDestinationsRoute,
  ApiWacrmFlowCompletedRoute: ApiWacrmFlowCompletedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
